src/components/common/button/WriteCompleteButton.jsx, src/components/common/button/WriteCompleteButton.style.js, src/styles/color.js, src/styles/font.js
작품등록 페이지, 마이페이지에 공통으로 쓰이는 작성 완료 버튼 컴포넌트 생성
=> feat: 작성 완료 버튼 컴포넌트 생성

package.json, src/components/common/category/Category.jsx, src/components/common/category/Category.style.js, yarn.lock
#15 
카테고리 컴포넌트 생성
- MUI 라이브러리 [Chip] 사용 (package.json 수정됨)
=> feat: 카테고리 컴포넌트 생성

src/components/common/description/Description.jsx, src/components/common/description/Description.style.js
#14 
상세설명 컴포넌트 생성 
- margin 없이 100%로 채워서 생성
=> feat: 상세설명 컴포넌트 생성

src/Router.jsx, src/pages/Artist.jsx, src/pages/Auth/SignIn.jsx, src/pages/Main.jsx
#20
초기 라우팅 처리
- 초기 page 생성 완료
- 추후 자유롭게 page 생성하며 작업
=> Init: 초기 라우팅 처리

src/components/common/bottomNav/BottomNav.jsx, src/components/common/bottomNav/BottomNav.style.js, src/components/common/header/Header.jsx, src/components/common/header/Header.style.js, src/styles/color.js, src/styles/font.js
closed #63 
헤더바, 하단 네비게이션바 겹침현상 수정
=> fix: 헤더, 하단네비 수정

src/Router.jsx, src/components/common/bottomNav/BottomNav.style.js, src/components/common/header/Header.style.js, src/components/mypage/LogoutStatus.jsx, src/components/mypage/LogoutStatus.style.js, src/pages/MyPage.jsx, src/pages/myPage/MyPage.jsx, src/styles/color.js, src/styles/font.js
closed #65 
마이페이지 로그아웃상태 컴포넌트 생성
=> feat: 마이페이지 로그아웃상태 컴포넌트 생성

src/components/artist/reviewList/ReviewList.jsx, src/components/artist/temperature/Temperature.jsx, src/components/artist/temperature/Temperature.style.js, src/components/common/artworkList/RowArtWorkList.jsx, src/pages/artist/ArtistReviewList.jsx, src/styles/color.js
=> feat: 작가 상세 - 후기 페이지

src/Router.jsx, src/pages/Favorites.jsx, src/pages/favorites/Favorites.jsx, src/pages/favorites/Favorites.style.js
closed #57 
- 찜한 작품 페이지
- 현재는 dummy data이므로, 후에 data, filtering 작업 필요
=> feat: 관심 작품 페이지

src/components/common/description/Description.jsx, src/components/common/description/Description.style.js
#81 
- TextArea에 값 입력되면, Title 색 변경되게 수정
=> feat: 상세설명 컴포넌트 수정

src/pages/artwork/artworkDetail/ArtworkDetail.jsx, src/pages/artwork/artworkDetail/ArtworkDetail.style.js, src/pages/artwork/artworkDetail/MyArtworkDetail.jsx
closed #40
- 공통 컴포넌트 import 및 margin 조정
=> feat: 작품 상세 페이지 수정

src/assets/index.js, src/components/common/artwork/ArtWorkInfo.jsx, src/components/common/artwork/ArtWorkInfo.style.js, src/components/common/button/ReviewButton.style.js, src/components/common/button/WriteCompleteButton.jsx, src/components/common/button/WriteCompleteButton.style.js, src/components/common/myPage/ReviewDescription.jsx, src/components/common/myPage/ReviewDescription.style.js, src/pages/myPage/WriteReviewPage.jsx
closed #113 
후기 작성 페이지 생성.
작성완료 버튼은 type="WriteOffButton"처럼
type 지정해서 색 다르게 사용가능
=> feat: 후기 작성 페이지 생성

src/components/common/artworkList/ColumnArtworkList.jsx
closed #93
- react-stack-grid 라이브러리 대신, 직접 구현
=> feat: columnArtworkList react-stack-grid  라이브러리 마이그레이션

src/apis/api.js, src/apis/user.js, src/pages/auth/SignIn.jsx
#117
api 세팅
apis 폴더에 사용하는 api hook 생성 후 페이지에서 Import해서 사용
=> feat: api 세팅

src/components/common/category/Category.jsx, src/components/common/category/Category.style.js, src/components/common/category/CategoryList.jsx, src/constants/categoryDummy.js, src/constants/deliveryDummy.js
#61 
- 카테고리 컴포넌트 props로 어디에서나 사용 가능하게 수정 완료
- chip에 들어가는 항목은 dummy로 빼서 constants 폴더에 저장
=> feat: 카테고리 컴포넌트 수정 완료

src/components/modal/purchased/Buyer.Style.js, src/components/modal/purchased/Buyer.jsx, src/components/modal/purchased/PurchasedModal.jsx, src/components/modal/purchased/PurchasedModal.style.js
#121
- 구매자는 Buyer.jsx로 따로 컴포넌트를 분리했습니다
- 구매자 선택 모달창인 PurchasedModal.jsx에서 Buyer.jsx를 import하게 했습니다
< 미해결 이슈 >
- 라디오버튼 클릭하면 피그마처럼 보라색으로 바뀌게 하는 건 아직 성공하지 못했습니다,,
=> feat: 구매자 선택 모달 생성

src/components/modal/report/Reason.jsx, src/components/modal/report/Reason.style.js, src/components/modal/report/ReportModal.jsx, src/components/modal/report/ReportModal.style.js, src/constants/reportDummy.js
#122 
- 신고 이유는 dummy로 빼서 constant에 저장했습니다
- dummy로 뺀 신고 이유를 Reason.jsx에서 map으로 처리했습니다
- 신고 이유 선택 모달창인 ReportModal.jsx에서 Reason.jsx를 import 했습니다
< 미해결 이슈 >
- 라디오 버튼 클릭하면 피그마처럼 보라색으로 보이게 하는 건 아직 성공하지 못했습니다,,
=> feat: 신고하기 모달 생성

src/apis/api.js, src/components/common/button/SettingButton.style.js, src/components/common/menu/menu.style.js, src/components/common/myPage/PurchaseReviewList.jsx, src/components/common/myPage/PurchaseReviewList.style.js, src/pages/myPage/MyPage.jsx
closed #128
마이페이지 거래후기, 메뉴 컴포넌트 크기 화면에 맞게 수정
=> fix: 마이페이지 컴포넌트 크기 수정

src/components/common/category/Category.jsx
closed #61 
- 카테고리 컴포넌트 완성 
ㄴ 함수명 변경 (테스트 함수명 지움)
=> feat: 카테고리 컴포넌트 완성

src/apis/postRegister.js, src/pages/auth/SignUp.jsx
closed #130 
- 회원가입 페이지 api 연동
=> feat: register api 연동

src/pages/artwork/artworkUpload/ArtworkUpload.jsx, src/pages/artwork/artworkUpload/ArtworkUpload.style.js
#137
- 카테고리 컴포넌트 완성본 import
- 작성 완료 버튼 테스트
=> feat: 작품 등록 페이지 수정

src/apis/postRegister.js, src/components/common/artwork/ArtWork.jsx, src/components/common/button/PurchaseReviewButton.style.js, src/components/common/myPage/MyArtWorkList.jsx, src/components/mypage/LoginStatus.style.js, src/pages/auth/SignUp.jsx
closed #140 
마이페이지 크기 화면 넘치는 이슈 해결, 내 작품 favorite 안보이게 수정
=> fix: 마이페이지 크기 재설정, 내 작품 favorite 안보이게 수정

src/components/common/menu/menu.jsx, src/components/modal/LoginModal.jsx, src/components/modal/LoginModal.style.js, src/components/mypage/LogoutStatus.jsx, src/components/mypage/LogoutStatus.style.js, src/pages/artwork/artworkUpload/ArtworkUpload.jsx, src/pages/auth/SignIn.jsx, src/pages/chatting/ChattingList.jsx, src/pages/favorites/Favorites.jsx, src/pages/main/Main.jsx, src/pages/myPage/MyPage.jsx, src/recoil/atom.jsx
#151 
- 로그인 후 토큰 localStorage에 저장
- 닉네임, userId recoil에 저장
- 로그인 유무 판단(recoil) 후 접근 제한
=> feat: 토큰 저장, 접근권한 설정

src/apis/postProduct.js, src/components/common/category/CategoryList.jsx, src/pages/artwork/artworkUpload/ArtworkUpload.jsx
closed #156
작품 등록 form data로 전송완료
완료 후, 홈 화면으로 이동
=> feat: 작품 등록 완료

.env, src/apis/api.js, src/components/common/artwork/ArtWork.jsx, src/components/common/category/Category.jsx, src/components/common/category/CategoryList.jsx, src/pages/artwork/artworkDetail/ArtworkDetail.jsx, src/pages/artwork/artworkUpload/ArtworkUpload.jsx
closed #158
작품 등록 시, 카테고리, 배송방식 고정 값이 아니라 선택 가능하게 변경
authorId, nickname 로그인 된 정보로 불러와 전송하게 변경
.toLocaleString() 하면 금액에 저절로 . 붙어 나옵니다!
=> fix: 카테고리, 배송방식 선택 값으로 변경, authorId, nickname 불러오기

src/components/common/menu/menu.jsx, src/pages/artwork/artworkUpload/ArtworkUpload.jsx, src/pages/auth/SignIn.jsx, src/pages/chatting/ChattingList.jsx, src/pages/favorites/Favorites.jsx, src/pages/myPage/MyPage.jsx, src/recoil/atom.jsx, src/utils/isLogin.jsx
#162 
로그인상태 recoil 저장 -> 토큰 판단 으로 변경
=> fix: 새로고침 시 로그인 상태 유지

src/apis/getUserInfo.js, src/components/common/profile/Profile.jsx, src/components/mypage/LoginStatus.jsx, src/pages/artwork/artworkDetail/ArtworkDetail.jsx, src/pages/auth/SignIn.jsx, src/pages/main/Main.jsx
closed #165 
- 프로필 하드코딩 데이터 제거
=> refactor: 프로필 데이터

src/pages/artwork/artworkUpload/ArtworkUpload.jsx, yarn.lock
=> fix: merge conflict

package.json, src/apis/chatList.js, src/apis/chatLog.js, src/components/chatting/ChatList.jsx, src/components/chatting/infoBar/InfoBar.jsx, src/components/chatting/messages/Messages.jsx, src/pages/artwork/artworkDetail/ArtworkDetail.jsx, src/pages/chatting/Chatting.jsx, yarn.lock
#174
채팅 무한스크롤 구현
문제점 : 스크롤을 아래로 가게 설정했더니 불러올때 스크롤이 맨 위에서 아래로 내려감 -> 처음부터 스크롤을 맨아래로 하고싶은데 방법이 없을까요.. help,,
=> feat: 채팅 무한스크롤

src/apis/getProductList.js, src/pages/artist/ArtWorksList.jsx, src/pages/artist/Artist.jsx
resolved #179 
- 내 작품만 불러오기 api 연동
- Artist 페이지에서 useParams로 받아온 authorId를 props로 ArtworkList에 전달
- 백엔드에 authorId 쿼리로 넣어 요청
- authorId : 1 인 것만 불러와지는 것 확인 !
=> feature: 작가 작품만 불러오기 api 연동

src/apis/getChatBuyer.js, src/apis/getChatBuyerList.js, src/apis/patchDeal.js, src/components/artwork/CompleteBtn.jsx, src/components/modal/purchased/Buyer.Style.js, src/components/modal/purchased/Buyer.jsx, src/components/modal/purchased/PurchasedModal.jsx, src/components/modal/purchased/PurchasedModal.style.js, src/pages/artwork/artworkDetail/ArtworkDetail.jsx
resolved #183 
- 판매완료 버튼 눌렀을 때, 모달로 채팅한 문의자 리스트 뜨게 하기
- 채팅 기록이 없으면 -> 채팅 목록이 존재하지 않습니다
- 채팅 기록이 있으면 - 모달에 채팅한 문의자 리스트 띄우기 -> 판매완료 누르면 patch 되게
=> feat: 판매완료 기능 연결 및 api 연동

src/apis/api2.js, src/components/chatting/ChatList.jsx, src/components/chatting/ChatList.style.js, src/components/chatting/infoBar/InfoBar.jsx, src/components/chatting/messages/Messages.jsx, src/components/chatting/messages/message/Message.jsx, src/components/chatting/messages/message/Message.style.js, src/index.jsx, src/pages/chatting/Chatting.jsx, yarn.lock
#187 
채팅에 안읽은 목록 표시
채팅 읽음/안읽음(1)
=> feat: 채팅 읽음/안읽음

src/pages/favorites/Favorites.jsx, src/pages/main/Main.jsx
#195 
- 메인, 관심작품 페이지 - 무한스크롤 구현 완료
- 10개씩 불러와지게
=> feat: 메인, 관심작품 페이지 무한스크롤 구현 완료

src/apis/postReport.js, src/components/common/toast/Tost.style.js, src/components/modal/report/Reason.jsx, src/components/modal/report/ReportModal.jsx, src/components/modal/report/ReportModal.style.js, src/pages/artwork/artworkDetail/ArtworkDetail.jsx
#189
작품 신고 모달 창 띄우고 api 연결, 신고 완료 시 toast 띄움
=> feat: 작품 신고 기능
